name: Publish on release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to packagist.org
    steps:
      - name: Update packagist<>github
        run: curl -X POST -H'Content-Type:application/json' -d '{"repository":"https://github.com/${{ github.repository }}"}' 'https://packagist.org/api/update-package?username=${{ vars.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}'
